### ISSUE TITLE
Edit formis on sugu nõutud.

### ISSUE THREAD

**Issue by aaronuurman** [randopa/failid#1]
Kui muudad kirjeandmeid, siis sugu on nõutud.  See ei ole väga loogiline...

**Comment by randopa** [comment]
Korras!

**Comment by ragnarkurm** [comment]
Rando sai sellest vist valesti aru :)
Ta võttis selle välja juurest "required" ära,
kuid väli ise jäi.

Aaron mõtles seda, et tel nr vms kipub küll eagajalt vahetuma,
aga sugu peaks siiski konstantne olema.

Rando, veel 1 asi, mis pole küll selle issue teema, aga kui sa git-ga teed add, commit ja push, siis püüa sisukamad kommentaarid panna, muidu on raske jälgida su tegevust. Mis mõtet siis git-l on? Näiteks:

```
git add edit.html
git commit -m 'Soo välja eemaldamine edit vormilt.'
git push
```

See pole ju keeruline.

**Comment by ragnarkurm** [comment]
Aitäh Aaron, review eest!
