### ISSUE TITLE
Kasutaja registreerimisel, kontrolli sisendit.

### ISSUE THREAD

**Issue by aaronuurman** [randopa/failid#3]
Telefoni numbriks saab sisestada näiteks sõnasid.

**Comment by randopa** [comment]
Parandasin ära.

**Comment by ragnarkurm** [comment]
Sa võiksid vastava commiti siduda issuega, siis oleks lihtne näha kuidas parandasid. Edit vormilt saab tel nr kohale sisestada teksti. Sa tegid paranduse HTML-s, aga seda oleks tark teha php-s esimese asjana enne andmete edasist töötlemist. Sellegipoolest, parandasid oma rakenduse oma oskuste/võimete kohaselt. Selle õppeprojekti jaoks on see piisav.
