### ISSUE TITLE
Salvesta andmebaasi kogu teekond pildini.

### ISSUE THREAD

**Issue by aaronuurman** [randopa/failid#4]
See võibolla juuksekarva lõhki ajamine, aga kas poleks targem salvestada kogu teekond pildini andmebaasi, kui seda teekonda pildini korduvalt genereerida uuesti?

**Comment by aaronuurman** [comment]
Pole oluline.

**Comment by ragnarkurm** [comment]
Kui teekond pildini genereeritakse iga kord, siis on mõtet salvestada.
Kui see on olemas ühes konfiguratsiooni muutujas, siis vist pole mõtet.
